### ISSUE TITLE
dependency question for DataStreamer

### ISSUE THREAD

**Issue by eric-gardyn** [mongodb/chatbot#474]
It looks like DataStreamer was [moved](https://github.com/mongodb/chatbot/commit/ce46b840cef5d3c5310765b92261021943efaf25#) from mongo-chat-server services folder to use the version in mongodb-rag-core.

The latest version of the "mongodb-chatbot-server" is "0.9.1", which installs "mongodb-rag-core" version": "0.3.1".
However, it doesn't look like this version of the rag-core includes the DataStreamer file?

**Comment by mongodben** [comment]
> The latest version of the "mongodb-chatbot-server" is "0.9.1", which installs "mongodb-rag-core" version": "0.3.1".
> However, it doesn't look like this version of the rag-core includes the DataStreamer file

we are preparing new released of both mongodb-chatbot-server and mongodb-rag-core that'll have this updated. the current stuff on npm should work. 

and when we do the release with the consolidation of stuff in mongodb-rag-core, there will be no external breaking changes since mongodb-chatbot-server rexports everything from mongodb-rag-core
